-- --------------Création des tables
-- PIECE (NOP, DESIGNATION, COULEUR, POIDS) ;
CREATE TABLE PIECE(
       NOP NUMBER ,
       DESIGNATION VARCHAR2(100),
       COULEUR VARCHAR2(100),
       POIDS VARCHAR2(100)
);
-- SERVICE (NOS, INTITULE, LOCALISATION) ;
CREATE TABLE SERVICE(
    NOS NUMBER, 
    INTITULE VARCHAR2(100), 
    LOCALISATION VARCHAR2(100)
    );

-- ORDRE (NOP, NOS, QUANTITE) ;
CREATE TABLE ORDRE (
    NOP NUMBER,
    NOS NUMBER, 
    QUANTITE VARCHAR2(100)) ;

    -- NOMENCLATURE (NOPA, NOPC, QUANTITE) ;

CREATE TABLE NOMENCLATURE (
    NOPA NUMBER,
    NOPC NUMBER,
    QUANTITE VARCHAR2(100)) ;    

-- --------------Contraintes d’intégrité

-- 1

INSERT INTO PIECE
VALUES(1,NULL,NULL,NULL);
VALUES(1,NULL,NULL,NULL);
VALUES(1,NULL,NULL,NULL);

--  2

INSERT INTO SERVICE
VALUES(1,NULL,NULL);
VALUES(1,NULL,NULL);
VALUES(1,NULL,NULL);

--  3

INSERT INTO ORDRE
VALUES(1,2,NULL);
VALUES(1,3,NULL);
VALUES(1,6,NULL);

-- 4

INSERT INTO NOMENCLATURE
VALUES(1,2,NULL);
VALUES(1,3,NULL);
VALUES(1,6,NULL);

--  7 
ALTER TABLE 
ADD Contrainte pce_col_ck check (COULEUR (COULEUR IN ('BLEU','ROUGE','JAUNE','NOIR')));

-- Modification de la structure de la base
-- 1
ALTER TABLE PIECE
MODIFY(DESIGNATION NUMBER(100));













